apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 80
        readinessProbe:
          httpGet:
            path: /           ##to check the readiness of the pod, we can use the readiness probe. The readiness probe checks if the application is ready to serve traffic. If the readiness probe fails, the pod will be removed from the service endpoints and will not receive any traffic until it becomes ready again.
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 10
          failureThreshold: 3
          
