apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend  
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: 654654239448.dkr.ecr.us-east-1.amazonaws.com/myecrrepo:frontend
        ports:
        - containerPort: 80
        env:
        - name: frontend
          value: "FRONTEND APP"
---
apiVersion: v1
kind: Service
metadata:
  name: frontend  
spec:
  type: ClusterIP
  ports:
  - port: 80
  selector:
    app: frontend