apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment-green
spec:
  replicas: 3
  selector:
    matchLabels:
      app: myapp
      replica: green
  template:
    metadata:
      labels:
        app: myapp
        replica: green
    spec:
      containers:
      - name: nginx-container
        image: nginx
        ports:
        - containerPort: 80 